config/routes.rb
Rails.application.routes.draw do

  patch 'tweets/:id' => 'tweets#update'
  get 'tweets/:id/edit' => 'tweets#edit', as:'edit_tweet'


  get 'maps/index'
  get 'maps///maps'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show]

  resources :tweets do
    resources :likes, only: [:create, :destroy]
  end
  resources :maps, only: [:index]

  get 'index2' => 'tweets#index2'

root "tweets#index"  


  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/tag.rb
class Tag < ApplicationRecord
    validates :name, presence: true
    has_many :tweet_tag_relations, dependent: :destroy
    has_many :tweets, through: :tweet_tag_relations, dependent: :destroy
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    has_one_attached :photo
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :tweet_tag_relations, dependent: :destroy
    has_many :tags, through: :tweet_tag_relations, dependent: :destroy
end

app/models/tweet_tag_relation.rb
class TweetTagRelation < ApplicationRecord
  belongs_to :tweet
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet
  has_many :tweets, dependent: :destroy
  validates :name, presence: true
  validates :profile, length: { maximum: 200 }

  has_one_attached :photo

  def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
      # サインアップ時にnameのストロングパラメータを追加
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :photo])
      # アカウント編集の時にnameとprofileのストロングパラメータを追加
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :photo])
    end
    
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
    def index
    end

    def link
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create
        like = current_user.likes.create(tweet_id: params[:tweet_id]) #user_idとtweet_idの二つを代入
        redirect_back(fallback_location: root_path)
    end
    
    def destroy
        like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
    end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index
  end

  def maps
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :authenticate_user!
    def index
        @tweets = Tweet.all
    search = params[:search]
    @tweets = @tweets.joins(:user).where("body LIKE ?", "%#{search}%") if search.present?
    @tweets = @tweets.page(params[:page]).per(3)
    @rank_tweets = Tweet.all.sort {|a,b| b.liked_users.count <=> a.liked_users.count}.first(3)
    if params[:tag_ids].present?
      tweet_ids = []
      params[:tag_ids].each do |key, value| 
        if value == "1"
          Tag.find_by(name: key).tweets.each do |p| 
            tweet_ids << p.id
          end
        end
      end
      tweet_ids = tweet_ids.uniq
      #キーワードとタグのAND検索
      @tweets = @tweets.where(id: tweet_ids) if tweet_ids.present?
    end
    end

    def index2
      @tweets = Tweet.all
  search = params[:search]
  @tweets = @tweets.joins(:user).where("body LIKE ?", "%#{search}%") if search.present?
  @tweets = @tweets.page(params[:page]).per(3)
  @rank_tweets = Tweet.all.sort {|a,b| b.liked_users.count <=> a.liked_users.count}.first(3)
  if params[:tag_ids].present?
    tweet_ids = []
    params[:tag_ids].each do |key, value| 
      if value == "1"
        Tag.find_by(name: key).tweets.each do |p| 
          tweet_ids << p.id
        end
      end
    end
    tweet_ids = tweet_ids.uniq
    #キーワードとタグのAND検索
    @tweets = @tweets.where(id: tweet_ids) if tweet_ids.present?
  end
  end

    def new
        @tweet = Tweet.new
    end

    def create
        tweet = Tweet.new(tweet_params)

        tweet.user_id = current_user.id

        if tweet.save
         redirect_to :action => "index"
        else
         redirect_to :action => "new"
        end
      end
      def show
        @tweet = Tweet.find(params[:id])
      end

      def edit
        @tweet = Tweet.find(params[:id])
      end

      def update
        tweet = Tweet.find(params[:id])
        if tweet.update(tweet_params)
          redirect_to :action => "show", :id => tweet.id
        else
          redirect_to :action => "new"
        end
      end
      def destroy
      tweet = Tweet.find(params[:id])
      tweet.destroy
      redirect_to action: :index
    end

    private
      def tweet_params
        params.require(:tweet).permit(:title, :spot, :body, :chain, :photo, :lat,:lng, tag_ids: [])
      end

      
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
    end

    def edit
        @tweet = Tweet.find(params[:id])
    end
    def update
        tweet = Tweet.find(params[:id])
        if tweet.update(tweet_params)
          redirect_to :action => "show", :id => tweet.id
        else
          redirect_to :action => "new"
        end
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hello/index.html.erb
<%= link_to "ログイン", tweets_path %>
<%= link_to "新規登録", new_user_registration_path %>

app/views/hello/link.html.erb
My name is GeekSalon.
<%= link_to 'トップページ', hello_index_path %>
<%= link_to '一覧表示', tweets_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Michi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1 href="https://fontmeme.com/ja/font-pixel-style/"><img src="https://fontmeme.com/permalink/240719/4f6c721c7cf8955c2aec6855b0a6f055.png" alt="font-pixel-style" border="0"></h1>
      <div class="header-list">
      
    <ul>

      
        <li><%= link_to "新規投稿ページへ", new_tweet_path %></li>
      
      
        <li><%= link_to "投稿一覧へ", index2_path %></li>
      
      
        <li><%= link_to "Tweet一覧に戻る", tweets_path %></li>
      
      
        <% if user_signed_in? %>
      <li><%= link_to "マイページへ", user_path(current_user.id) %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete%></li>
        <% end %>
    

    </ul>
    
  </div>
 
    </header>
    <div class=main2>
    <main>
    <%= yield %>
    </main>
    </div>
  </body>
</html>

app/views/maps/index.html.erb
<h1>Maps#index</h1>

<p>Find me in app/views/maps/index.html.erb</p>

<h2>gmap</h2>
<input id="address" type="textbox" value="GeekSalon">
<input type="button" value="Encode" onclick="codeAddress()">
<div id='map'></div>
<style>
#map{
  height: 400px;
}

</style>

<script>
let map
function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: 40.7828, lng:-73.9653},
    zoom: 12,
  });

  marker = new google.maps.Marker({
    position:  {lat: 40.7828, lng:-73.9653},
    map: map
  });
}
let geocoder

function codeAddress(){
  let inputAddress = document.getElementById('address').value;

  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
      map.setCenter(results[0].geometry.location);
      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });
    } else {
      alert('該当する結果がありませんでした：' + status);
    }
  });   
}
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAVHSs6WHc3r79E_G96T1-iiUnPNvDfXgk&callback=initMap" async defer></script>

app/views/maps/maps.html.erb
<h1>Maps#//maps</h1>
<p>Find me in app/views/maps//maps.html.erb</p>

app/views/tweets/edit.html.erb
<%= form_for @tweet do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, :size => 140 %> 
  <%= f.label :spot %>
  <%= f.text_field :spot, :size => 140 %>
  <%= f.label :body %>
  <%= f.text_area :body, :size => "30x2" %>
  <%= f.label :chain %>
  <%= f.text_field :chain, :size => 140 %>
  <%= f.label :photo %>
  <%= f.file_field :photo %>
  <%= f.submit "編集する" %>
<% end %>

app/views/tweets/index.html.erb
<html>
<body>
<div class="lank">
<span>ランキング</span>
</div>

<div class="tweets">
<% @rank_tweets.each do |t| %>
  <div class="tweet">
      <% if t.photo.attached? %>
        <%= image_tag t.photo, size: '100x80' %>
      <% end %>
      <p><%= t.title %></p>
      <p><%= t.spot %></p>
      <% if user_signed_in? %>
        <% if current_user.already_liked?(t) %>
          <%= button_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
            <p>知らなかった！を取り消す</p>
            <%= t.likes.count %>
          <% end %>
        <% else %>
          <%= button_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :tweet do %>
            <p>知らなかった！</p>
            <%= t.likes.count %>
          <% end %>
        <% end %>
      <% else %>
        <%= t.likes.count %>
      <% end %>
      <p><%= t.created_at %></p>
      
      
    </div>

 <% end %>
   </div>
<div class="maru1" href="~">1</div>
<div class="maru2" href="~">2</div>
<div class="maru3" href="~">3</div>
<%= link_to '地図', maps_index_path %>
<div id='map'></div>

<style>
#map {
  height: 600px;
  width: 100%;
}
</style>

<!-- js部分 -->
<script>
    function initMap() {

      //初期表示位置
      let latlng = new google.maps.LatLng(38.60, 139.5);
      //デザイン
      let styles = [
           {
            stylers: [
             { "saturation": 0 },
             { "lightness": 0 }
            ]
           }
          ];

      let map = new google.maps.Map(document.getElementById('map'), {
          zoom: 5.5,
          styles: styles,
          center: latlng
      });
      let transitLayer = new google.maps.TransitLayer();
      transitLayer.setMap(map);

//複数マーカー ここから
      <% @tweets.each do |tweet|%>
        ( function() { 
          let markerLatLng = { lat: <%= tweet.lat %>, lng: <%= tweet.lng %> }; // 緯度経度のデータ作成
          let marker = new google.maps.Marker({ 
            position: markerLatLng, 
            map: map 
          });
//マーカーをクリックしたとき、詳細情報を表示
          let infowindow = new google.maps.InfoWindow({
            position: markerLatLng,
            content: "<a href='<%= tweet_url(tweet.id) %>' target='_blank'><%= tweet.body %></a>"
          }); //ここで詳細ページへのリンクを表示させる
          marker.addListener('click', function() {
            infowindow.open(map, marker);
          });

       })();
      <% end %>
      //複数マーカー ここまで  
  }
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAVHSs6WHc3r79E_G96T1-iiUnPNvDfXgk&callback=initMap" async defer></script>

<div class="form-container4">
<div class="form-container3">
<h3>Tweet検索</h3>
<div class="form-container2">
<%= form_tag({controller: "tweets", action: "index"}, method: :get) do %>
  <%= text_field_tag :search %>
  <%= submit_tag '検索する' %>
<% end %>
 <%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
    <% Tag.all.each do |t| %>
        <li><%= check_box :tag_ids, t.name %><%= t.name %></li>
    <% end %>
    <%= submit_tag '検索' %>
</div>
</div>
</div>
</body>
</html>
<!--<%= page_entries_info @tweets %>
<%= paginate @tweets %>
<div class="tweets-container">
  <% @tweets.each do |t| %>
    <div class="tweet">
       <%= t.user.email %>
       <% if t.user.photo.attached? %>
        <%= image_tag t.user.photo, size: '250x200'%>
    <% end %>
      <% if t.photo.attached? %>
        <%= image_tag t.photo, size: '250x200' %>
      <% end %>
      <p><%= t.title %></p>
      <p><%= t.spot %></p>
      <p><%= t.body %></p>
      <% if user_signed_in? %>
        <% if current_user.already_liked?(t) %>
          <%= button_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
            <p>知らなかった！を取り消す</p>
            <%= t.likes.count %>
          <% end %>
        <% else %>
          <%= button_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :tweet do %>
            <p>知らなかった！</p>
            <%= t.likes.count %>
          <% end %>
        <% end %>
      <% else %>
        <%= t.likes.count %>
  <% end %>
      <p><%= t.chain %></p>
      <p><%= t.created_at %></p>
      <%= link_to "詳細へ", tweet_path(t.id) %>
      <% if user_signed_in? && current_user.id == t.user_id %>
      <%= link_to "編集する", edit_tweet_path(t.id) %>
      <%= link_to "削除する", tweet_path(t.id), method: :delete %>
      <% end %>

     
<% end %>
      
    </div>
  <% end %>
</div>-->

app/views/tweets/index2.html.erb
<div class="form-container4">
<div class="form-container3">
<%= stylesheet_link_tag 'tweets_index2', :media => "all" %>
<h3>Tweet検索</h3>

<%= form_tag({controller: "tweets", action: "index2"}, method: :get) do %>
  <%= text_field_tag :search %>
  <%= submit_tag '検索する' %>
<% end %>
 <%= form_tag({controller:"tweets",action:"index2"}, method: :get) do %>
    <% Tag.all.each do |t| %>
        <li><%= check_box :tag_ids, t.name %><%= t.name %></li>
    <% end %>
    <%= submit_tag '検索' %>
</div>
</div>
<%= page_entries_info @tweets %>


<%= paginate @tweets %>
  <% @tweets.each do |t| %>
    <div class="center">
    <div class="center2">
    <div class="flex">
    <div class="kakomi">
    <figure class="image"> <% if t.photo.attached? %>
        <%= image_tag t.photo, size: '270x200'%>
    <% end %>
    </figure>
    </div>

      <ol>
      <p >なまえ : <%= t.title %></p>
      <p >ばしょ:  <%= t.spot %></p>
      <p >りんく : <%= Rinku.auto_link(t.chain, :all, 'target="_blank"').html_safe  %></p>
      <p class="bottom_space">投稿者 : <%= t.user.email %></p>
      <p><%= t.created_at %></p>
      </ol>
    </div>
    </div>
    
    <div class="shousai">
      <%= t.body %>
      <% if user_signed_in? %>
        <% if current_user.already_liked?(t) %>
          <%= button_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
            <p>知らなかった！を取り消す</p>
            <%= t.likes.count %>
          <% end %>
        <% else %>
          <%= button_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :tweet do %>
            <p>知らなかった！</p>
            <%= t.likes.count %>
          <% end %>
        <% end %>
      <% else %>
        <%= t.likes.count %>
  <% end %>
      </div>
      
    
    <div class="right">
      <%= link_to "詳細へ", tweet_path(t.id),class:"btn-gradient-3d"%>
      <% if user_signed_in? && current_user.id == t.user_id %>
      <%= link_to "編集する", edit_tweet_path(t.id),class:"btn-gradient-3d" %>
      <%= link_to "削除する", tweet_path(t.id), method: :delete ,class:"btn-gradient-3d"%>
      <% end %>
    </div>
    </div>

     
<% end %>
      
    </div>
  <% end %>
</div>

app/views/tweets/new.html.erb
<html lang="ja">
<body>

<h3>新規Tweet</h3>
<div class="blank1">
<%= form_for @tweet do |f| %>
  <div class="field">
    <%= f.label :タイトル %>
    <%= f.text_field :title, :size => 100 %>
  </div>
    
  <div class="field">
    <%= f.label :場所・・ %>
    <%= f.text_field :spot, :size => 100 %>
    </div>

  
    <p><%= f.label :説明・・ %>
    <%= f.text_area :body, :size => "30x2" %></p>
  
    <p><%= f.label :リンク・ %>
    <%= f.text_field :chain, :size => 100 %></p>
  
    <p><%= f.label :画像・・ %>
    <%= f.file_field :photo %></p>
 
  
    <p><%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
            <div class='form-check'>
                <%= tag.label class: 'form-check-label' do %>
                    <%= tag.check_box class: 'form-check-input' %>
                    <%= tag.text %>
                <% end %>
            </div>
        <% end %></p>
 
  </div>
    

<div class="field">
  <%= f.label :lat,"緯度" %>
    <%= f.text_field :lat,:placeholder =>"緯度", id: :lat %>
    <%= f.label :lng,"経度" %>
    <%= f.text_field :lng,:placeholder =>"経度", id: :lng %>
  <%= f.submit "Tweetする" %>
<% end %>


<div class="moji">
<h2>Map</h2>
</div>

<input id="address" type="textbox" value="GeekSalon">
<input type="button" value="検索" onclick="codeAddress()">
<p>マーカーをドラック＆ドロップで位置の調整ができます。<p>
<div id='map'></div>

</div>

<style>
#map {
  height: 600px;
  width: 600px;
  margin: 0 auto;
}
</style>

<script>
//初期マップの設定
let map
let marker
function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center:  {lat: 35.6803997, lng:139.7690174},  //東京
    zoom: 15,
    
  });
}

//検索後のマップ作成
let geocoder
let aft
function codeAddress(){
  let inputAddress = document.getElementById('address').value;
  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
        //マーカーが複数できないようにする
        if (aft == true){
            marker.setMap(null);
        }

        //新しくマーカーを作成する
        map.setCenter(results[0].geometry.location);
            marker = new google.maps.Marker({
            map: map,
            position: results[0].geometry.location,
            draggable: true	// ドラッグ可能にする
        });

        //二度目以降か判断
        aft = true

        //検索した時に緯度経度を入力する
        document.getElementById('lat').value = results[0].geometry.location.lat();
        document.getElementById('lng').value = results[0].geometry.location.lng();

        // マーカーのドロップ（ドラッグ終了）時のイベント
        google.maps.event.addListener( marker, 'dragend', function(ev){
            // イベントの引数evの、プロパティ.latLngが緯度経度
            document.getElementById('lat').value = ev.latLng.lat();
            document.getElementById('lng').value = ev.latLng.lng();
        });
    } else {
      alert('該当する結果がありませんでした：' + status);
    }
  });   
}

</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAVHSs6WHc3r79E_G96T1-iiUnPNvDfXgk&callback=initMap" async defer></script>

</body>
</html>

app/views/tweets/show.html.erb
<h3>Tweet詳細</h3>
<div class="center">
    <div class="center2">
    <div class="flex">
    <div class="kakomi">
    <figure class="image">
  <% if @tweet.photo.attached? %>
    <%= image_tag @tweet.photo, size: '250x200'%>
  <% end %>
  </figure>
    </div>



<ol>
  <p>なまえ : <%= @tweet.title %>
  <p>タグ  : <% @tweet.tags.each do |tag| %><%= tag.name %></p>
<% end %></p>
  <p>ばしょ : <%= @tweet.spot %></p> 
  <p>りんく : <%= Rinku.auto_link(@tweet.chain, :all, 'target="_blank"').html_safe %></p>
  <p><%= @tweet.created_at %></p>
  </ol>
  </div>

  <div class="shousai">
    <p><%= @tweet.body %></p>
  <% if user_signed_in? %>
      <% if current_user.already_liked?(@tweet) %>
        <%= button_to tweet_like_path(@tweet), method: :delete do %>
          <p>知らなかった！を取り消す</p><%= @tweet.likes.count %>
        <% end %>
      <% else %>
        <%= button_to tweet_likes_path(@tweet), method: :post do %>
          <p>知らなかった！</p><%= @tweet.likes.count %>
        <% end %>
      <% end %>
    <% else %>
      <p>知らなかった！の数 = </p><%= @tweet.likes.count %>
    <% end %>
</div>

<div class="shiru">
<p>知らなかった！したユーザー</p>
<% @tweet.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>
</div>

<div class="right">
<%= link_to "編集する", edit_tweet_path(@tweet.id),class:"btn-gradient-3d" %> 
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<body>
<>
<h1>マイページ</h1>
<div class="oowaku">
<div class="gazou">
<% if @user.photo.attached? %>
        <%= image_tag @user.photo, size: '250x200'%>
<% end %>
</div>
<div class="profile">
<p>なまえ : <%= @user.name %></p>
<p>メール : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>
</div>
</div>


<div class="grandma">

<div class="ichiran-oya">
<div class="ichiran">
<span class="box-title">ユーザーの投稿一覧</span>
<% @user.tweets.each do |t| %>
  <p><%= t.title %></p>
  <p><%= t.body %></p>
  <%= link_to "編集する", edit_tweet_path(t.id) %>
  <%= button_to "削除する", tweet_path(t.id), method: :delete %>
<% end %>
</div>
</div>
</div>

<!-- 以下はいいね機能を実装している場合-->
<div class="henshu">
<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>
</div>

<div class="nice-ichiran-oya">
<div class="nice-ichiran">
<span class="box-title">ユーザーがいいねした投稿一覧</span>
<% @user.liked_tweets.each do |t| %>
  <p><%= t.user.name %></p>
  <p><%= t.title %></p>
<% end %>
</div>
<!-- ここまで-->
</div>
</div>
</div>
</body>